/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Personal
 */
public class Sistema extends javax.swing.JFrame {

    /**
     * Creates new form Sistema
     */
    public Sistema() {
        initComponents();
        //Centrar la venta en la pantalla
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_BarraBusqueda = new javax.swing.JPanel();
        jButton_NuevaVenta = new javax.swing.JButton();
        jButton_Clientes = new javax.swing.JButton();
        jButton_Proveedor = new javax.swing.JButton();
        jButton_Productos = new javax.swing.JButton();
        jButton_Ventas = new javax.swing.JButton();
        jButton_Información = new javax.swing.JButton();
        jLabel_Logo = new javax.swing.JLabel();
        jLabel_Img_Encabezado = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel_NuevaVenta = new javax.swing.JPanel();
        jLabel_CodigoProducto_Tab1 = new javax.swing.JLabel();
        jLabel_NombreProducto_Tab1 = new javax.swing.JLabel();
        jLabel_CantidadCompra_Tab1 = new javax.swing.JLabel();
        jLabel_PrecioCompra_Tab1 = new javax.swing.JLabel();
        jLabel_Stock_Tab1 = new javax.swing.JLabel();
        jButton_Eliminar_Tab1 = new javax.swing.JButton();
        jTextField_CodigoProducto_Tab1 = new javax.swing.JTextField();
        jTextField_NombreProducto_Tab1 = new javax.swing.JTextField();
        jTextField_CantidadCompra_Tab1 = new javax.swing.JTextField();
        jTextField_PrecioCompra_Tab1 = new javax.swing.JTextField();
        jTextField_Stock_Tab1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Venta_Tab1 = new javax.swing.JTable();
        jLabel_DocumentoCliente_Tab1 = new javax.swing.JLabel();
        jLabel_NombreCliente_Tab1 = new javax.swing.JLabel();
        jTextField_DocumentoCliente_Tab1 = new javax.swing.JTextField();
        jTextField_NombreCliente_Tab1 = new javax.swing.JTextField();
        jButton_GenerarVenta_Tab1 = new javax.swing.JButton();
        jLabel_TotalPagar_Tab1 = new javax.swing.JLabel();
        jLabel_ValorPagar_Tab1 = new javax.swing.JLabel();
        jTextField_DireccionCliente_Tab1 = new javax.swing.JTextField();
        jTextField_IDProducto_Tab1 = new javax.swing.JTextField();
        jPanel_Clientes = new javax.swing.JPanel();
        jLabel_DocumentoCliente_Tab2 = new javax.swing.JLabel();
        jLabel_NombreCliente_Tab2 = new javax.swing.JLabel();
        jLabel_TelefonoCliente_Tab2 = new javax.swing.JLabel();
        jLabel_CorreoCliente_Tab2 = new javax.swing.JLabel();
        jLabel_DireccionCliente_Tab2 = new javax.swing.JLabel();
        jTextField_DocumentoCliente_Tab2 = new javax.swing.JTextField();
        jTextField_NombreCliente_Tab2 = new javax.swing.JTextField();
        jTextField_TelefonoCliente_Tab2 = new javax.swing.JTextField();
        jTextField_CorreoCliente_Tab2 = new javax.swing.JTextField();
        jTextField_DireccionCliente_Tab2 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Clientes = new javax.swing.JTable();
        jButton_GuardarCliente_Tab2 = new javax.swing.JButton();
        jButton_ActualizarCliente_Tab2 = new javax.swing.JButton();
        jButton_EliminarCliente_Tab2 = new javax.swing.JButton();
        jButton_NuevoCliente_Tab2 = new javax.swing.JButton();
        jTextField_IDCliente_Tab2 = new javax.swing.JTextField();
        jPanel_Proveedor = new javax.swing.JPanel();
        jLabel_DocumentoProveedor_Tab3 = new javax.swing.JLabel();
        jLabel_NombreProveedor_Tab3 = new javax.swing.JLabel();
        jLabel_DireccionProveedor_Tab3 = new javax.swing.JLabel();
        jLabel_TelefonoProveedor_Tab3 = new javax.swing.JLabel();
        jLabel_CodigoProducto_Tab3 = new javax.swing.JLabel();
        jTextField_DocumentoProveedor_Tab3 = new javax.swing.JTextField();
        jTextField_NombreProveedor_Tab3 = new javax.swing.JTextField();
        jTextFieldl_DireccionProveedor_Tab3 = new javax.swing.JTextField();
        jTextField_TelefonoProveedor_Tab3 = new javax.swing.JTextField();
        jTextField_CodigoProducto_Tab3 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_Proveedores = new javax.swing.JTable();
        jButton_GuardarProveedor_Tab3 = new javax.swing.JButton();
        jButton_NuevoProveedor_Tab3 = new javax.swing.JButton();
        jButton_EliminarProveedor_Tab3 = new javax.swing.JButton();
        jButton_ActualizarProveedor_Tab3 = new javax.swing.JButton();
        jTextField_IDProveedor_Tab3 = new javax.swing.JTextField();
        jPanel_Productos = new javax.swing.JPanel();
        jLabel_CodigoProducto_Tab4 = new javax.swing.JLabel();
        jLabel_NombreProducto_Tab4 = new javax.swing.JLabel();
        jLabel_CantidadProducto_Tab4 = new javax.swing.JLabel();
        jLabel_PrecioVenta_Tab4 = new javax.swing.JLabel();
        jLabel_PrecioCompra_Tab4 = new javax.swing.JLabel();
        jTextField_CodigoProducto_Tab4 = new javax.swing.JTextField();
        jTextField_NombreProducto_Tab4 = new javax.swing.JTextField();
        jTextField_CantidadProducto_Tab4 = new javax.swing.JTextField();
        jTextField_PrecioVenta_Tab4 = new javax.swing.JTextField();
        jTextField_PrecioCompra_Tab4 = new javax.swing.JTextField();
        jLabel_ProveedorProducto_Tab4 = new javax.swing.JLabel();
        jComboBox_ProveedorProducto_Tab4 = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable_Productos = new javax.swing.JTable();
        jButton_GuardarProducto_Tab4 = new javax.swing.JButton();
        jButton_ActualizarProducto_Tab4 = new javax.swing.JButton();
        jButton_BorrarProducto_Tab4 = new javax.swing.JButton();
        jButton_NuevoProducto_Tab4 = new javax.swing.JButton();
        jButton_GenerarReporte_Tab4 = new javax.swing.JButton();
        jTextField_IDProducto_Tab4 = new javax.swing.JTextField();
        jPanel_Ventas = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jTextField_IDVenta_Tab5 = new javax.swing.JTextField();
        jPanel_Informacion = new javax.swing.JPanel();
        jLabel_NIT_Empresa = new javax.swing.JLabel();
        jLabel_Nombre_Empresa = new javax.swing.JLabel();
        jLabel_Telefono_Empresa = new javax.swing.JLabel();
        jLabel_Direccion_Empresa = new javax.swing.JLabel();
        jLabel_DatosEmpresa = new javax.swing.JLabel();
        jTextField_NIT_Empresa = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField_Telefono_Empresa = new javax.swing.JTextField();
        jTextField_Direccion_Empresa = new javax.swing.JTextField();
        jButton_Guardar_DatosEmpresa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Ventas de Productos Electrónicos");

        jPanel_BarraBusqueda.setBackground(new java.awt.Color(0, 5, 48));

        jButton_NuevaVenta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_NuevaVenta.setText("Nueva Venta");

        jButton_Clientes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Clientes.setText("Clientes");

        jButton_Proveedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Proveedor.setText("Proveedor");

        jButton_Productos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Productos.setText("Productos");

        jButton_Ventas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Ventas.setText("Ventas");

        jButton_Información.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Información.setText("Información");

        jLabel_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel_BarraBusquedaLayout = new javax.swing.GroupLayout(jPanel_BarraBusqueda);
        jPanel_BarraBusqueda.setLayout(jPanel_BarraBusquedaLayout);
        jPanel_BarraBusquedaLayout.setHorizontalGroup(
            jPanel_BarraBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BarraBusquedaLayout.createSequentialGroup()
                .addGroup(jPanel_BarraBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_BarraBusquedaLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel_Logo))
                    .addGroup(jPanel_BarraBusquedaLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel_BarraBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_NuevaVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_Clientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_Proveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_Productos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_Ventas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_Información, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel_BarraBusquedaLayout.setVerticalGroup(
            jPanel_BarraBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_BarraBusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Logo)
                .addGap(81, 81, 81)
                .addComponent(jButton_NuevaVenta)
                .addGap(37, 37, 37)
                .addComponent(jButton_Clientes)
                .addGap(46, 46, 46)
                .addComponent(jButton_Proveedor)
                .addGap(41, 41, 41)
                .addComponent(jButton_Productos)
                .addGap(40, 40, 40)
                .addComponent(jButton_Ventas)
                .addGap(40, 40, 40)
                .addComponent(jButton_Información)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jLabel_Img_Encabezado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/encabezado.jpg"))); // NOI18N

        jLabel_CodigoProducto_Tab1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_CodigoProducto_Tab1.setText("Codigo de Producto:");

        jLabel_NombreProducto_Tab1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_NombreProducto_Tab1.setText("Nombre:");

        jLabel_CantidadCompra_Tab1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_CantidadCompra_Tab1.setText("Cantidad:");

        jLabel_PrecioCompra_Tab1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_PrecioCompra_Tab1.setText("Precio:");

        jLabel_Stock_Tab1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_Stock_Tab1.setText("Stock:");

        jButton_Eliminar_Tab1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton_Eliminar_Tab1.setText("Eliminar");

        jTextField_CodigoProducto_Tab1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextField_NombreProducto_Tab1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextField_CantidadCompra_Tab1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextField_PrecioCompra_Tab1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextField_Stock_Tab1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTable_Venta_Tab1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable_Venta_Tab1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Cantidad", "Precio", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_Venta_Tab1);
        if (jTable_Venta_Tab1.getColumnModel().getColumnCount() > 0) {
            jTable_Venta_Tab1.getColumnModel().getColumn(0).setPreferredWidth(30);
            jTable_Venta_Tab1.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTable_Venta_Tab1.getColumnModel().getColumn(2).setPreferredWidth(30);
            jTable_Venta_Tab1.getColumnModel().getColumn(3).setPreferredWidth(30);
            jTable_Venta_Tab1.getColumnModel().getColumn(4).setPreferredWidth(40);
        }

        jLabel_DocumentoCliente_Tab1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_DocumentoCliente_Tab1.setText("Documento:");

        jLabel_NombreCliente_Tab1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_NombreCliente_Tab1.setText("Nombre:");

        jTextField_DocumentoCliente_Tab1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextField_NombreCliente_Tab1.setEditable(false);
        jTextField_NombreCliente_Tab1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_NombreCliente_Tab1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_NombreCliente_Tab1ActionPerformed(evt);
            }
        });

        jButton_GenerarVenta_Tab1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton_GenerarVenta_Tab1.setText("Generar Venta");

        jLabel_TotalPagar_Tab1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_TotalPagar_Tab1.setText("Total a Pagar:");

        jLabel_ValorPagar_Tab1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_ValorPagar_Tab1.setText("........");

        javax.swing.GroupLayout jPanel_NuevaVentaLayout = new javax.swing.GroupLayout(jPanel_NuevaVenta);
        jPanel_NuevaVenta.setLayout(jPanel_NuevaVentaLayout);
        jPanel_NuevaVentaLayout.setHorizontalGroup(
            jPanel_NuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_NuevaVentaLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel_NuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_NuevaVentaLayout.createSequentialGroup()
                        .addComponent(jTextField_IDProducto_Tab1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_TotalPagar_Tab1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_ValorPagar_Tab1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel_NuevaVentaLayout.createSequentialGroup()
                        .addGroup(jPanel_NuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_NuevaVentaLayout.createSequentialGroup()
                                .addGroup(jPanel_NuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_CodigoProducto_Tab1)
                                    .addComponent(jTextField_CodigoProducto_Tab1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel_NuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_NombreProducto_Tab1)
                                    .addComponent(jTextField_NombreProducto_Tab1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel_NuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_CantidadCompra_Tab1)
                                    .addComponent(jTextField_CantidadCompra_Tab1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel_NuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_PrecioCompra_Tab1)
                                    .addComponent(jTextField_PrecioCompra_Tab1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel_NuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_Stock_Tab1)
                                    .addComponent(jTextField_Stock_Tab1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jButton_Eliminar_Tab1)
                                .addGap(36, 36, 36)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel_NuevaVentaLayout.createSequentialGroup()
                        .addGroup(jPanel_NuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_NuevaVentaLayout.createSequentialGroup()
                                .addComponent(jLabel_DocumentoCliente_Tab1)
                                .addGap(126, 126, 126)
                                .addComponent(jLabel_NombreCliente_Tab1))
                            .addGroup(jPanel_NuevaVentaLayout.createSequentialGroup()
                                .addComponent(jTextField_DocumentoCliente_Tab1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_NombreCliente_Tab1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_DireccionCliente_Tab1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_GenerarVenta_Tab1)
                        .addGap(251, 251, 251))))
        );
        jPanel_NuevaVentaLayout.setVerticalGroup(
            jPanel_NuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_NuevaVentaLayout.createSequentialGroup()
                .addGroup(jPanel_NuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_NuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel_NuevaVentaLayout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addGroup(jPanel_NuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel_CodigoProducto_Tab1)
                                .addComponent(jLabel_NombreProducto_Tab1)
                                .addComponent(jLabel_CantidadCompra_Tab1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel_NuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField_CodigoProducto_Tab1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_NombreProducto_Tab1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_CantidadCompra_Tab1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_NuevaVentaLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel_NuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_NuevaVentaLayout.createSequentialGroup()
                                    .addComponent(jLabel_Stock_Tab1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField_Stock_Tab1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_NuevaVentaLayout.createSequentialGroup()
                                    .addComponent(jLabel_PrecioCompra_Tab1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField_PrecioCompra_Tab1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel_NuevaVentaLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jButton_Eliminar_Tab1)))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel_NuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_NuevaVentaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_NuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_ValorPagar_Tab1)
                            .addComponent(jLabel_TotalPagar_Tab1))
                        .addGap(9, 9, 9)
                        .addComponent(jButton_GenerarVenta_Tab1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_NuevaVentaLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jTextField_IDProducto_Tab1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_NuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_DocumentoCliente_Tab1)
                            .addComponent(jLabel_NombreCliente_Tab1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_NuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_DocumentoCliente_Tab1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_NombreCliente_Tab1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_DireccionCliente_Tab1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", jPanel_NuevaVenta);

        jLabel_DocumentoCliente_Tab2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_DocumentoCliente_Tab2.setText("Documento:");

        jLabel_NombreCliente_Tab2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_NombreCliente_Tab2.setText("Nombre Completo:");

        jLabel_TelefonoCliente_Tab2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_TelefonoCliente_Tab2.setText("Teléfono:");

        jLabel_CorreoCliente_Tab2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_CorreoCliente_Tab2.setText("Correo:");

        jLabel_DireccionCliente_Tab2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_DireccionCliente_Tab2.setText("Dirección:");

        jTextField_DocumentoCliente_Tab2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextField_NombreCliente_Tab2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextField_TelefonoCliente_Tab2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextField_CorreoCliente_Tab2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextField_DireccionCliente_Tab2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTable_Clientes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable_Clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Documento", "Nombre", "Teléfono", "Dirección", "Correo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable_Clientes);
        if (jTable_Clientes.getColumnModel().getColumnCount() > 0) {
            jTable_Clientes.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTable_Clientes.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTable_Clientes.getColumnModel().getColumn(2).setPreferredWidth(50);
            jTable_Clientes.getColumnModel().getColumn(3).setPreferredWidth(80);
            jTable_Clientes.getColumnModel().getColumn(4).setPreferredWidth(80);
        }

        jButton_GuardarCliente_Tab2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_GuardarCliente_Tab2.setText("Guardar");
        jButton_GuardarCliente_Tab2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton_ActualizarCliente_Tab2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_ActualizarCliente_Tab2.setText("Actualizar");
        jButton_ActualizarCliente_Tab2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton_EliminarCliente_Tab2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_EliminarCliente_Tab2.setText("Eliminar");
        jButton_EliminarCliente_Tab2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton_NuevoCliente_Tab2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_NuevoCliente_Tab2.setText("Nuevo");
        jButton_NuevoCliente_Tab2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel_ClientesLayout = new javax.swing.GroupLayout(jPanel_Clientes);
        jPanel_Clientes.setLayout(jPanel_ClientesLayout);
        jPanel_ClientesLayout.setHorizontalGroup(
            jPanel_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ClientesLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_ClientesLayout.createSequentialGroup()
                        .addGroup(jPanel_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_DireccionCliente_Tab2)
                            .addComponent(jLabel_CorreoCliente_Tab2)
                            .addComponent(jLabel_TelefonoCliente_Tab2)
                            .addComponent(jLabel_NombreCliente_Tab2)
                            .addGroup(jPanel_ClientesLayout.createSequentialGroup()
                                .addComponent(jTextField_IDCliente_Tab2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_DocumentoCliente_Tab2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_DocumentoCliente_Tab2)
                            .addComponent(jTextField_NombreCliente_Tab2)
                            .addComponent(jTextField_TelefonoCliente_Tab2)
                            .addComponent(jTextField_CorreoCliente_Tab2)
                            .addComponent(jTextField_DireccionCliente_Tab2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel_ClientesLayout.createSequentialGroup()
                        .addGroup(jPanel_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_EliminarCliente_Tab2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_GuardarCliente_Tab2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_ActualizarCliente_Tab2, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                            .addComponent(jButton_NuevoCliente_Tab2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_ClientesLayout.setVerticalGroup(
            jPanel_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ClientesLayout.createSequentialGroup()
                .addGroup(jPanel_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_ClientesLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_DocumentoCliente_Tab2)
                            .addComponent(jTextField_DocumentoCliente_Tab2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_IDCliente_Tab2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_NombreCliente_Tab2)
                            .addComponent(jTextField_NombreCliente_Tab2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_TelefonoCliente_Tab2)
                            .addComponent(jTextField_TelefonoCliente_Tab2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_CorreoCliente_Tab2)
                            .addComponent(jTextField_CorreoCliente_Tab2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_DireccionCliente_Tab2)
                            .addComponent(jTextField_DireccionCliente_Tab2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_NuevoCliente_Tab2)
                            .addComponent(jButton_GuardarCliente_Tab2))
                        .addGap(68, 68, 68)
                        .addGroup(jPanel_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_ActualizarCliente_Tab2)
                            .addComponent(jButton_EliminarCliente_Tab2)))
                    .addGroup(jPanel_ClientesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", jPanel_Clientes);

        jLabel_DocumentoProveedor_Tab3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_DocumentoProveedor_Tab3.setText("Documento:");

        jLabel_NombreProveedor_Tab3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_NombreProveedor_Tab3.setText("Nombre:");

        jLabel_DireccionProveedor_Tab3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_DireccionProveedor_Tab3.setText("Dirección:");

        jLabel_TelefonoProveedor_Tab3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_TelefonoProveedor_Tab3.setText("Teléfono:");

        jLabel_CodigoProducto_Tab3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_CodigoProducto_Tab3.setText("Código de Producto:");

        jTextField_DocumentoProveedor_Tab3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextField_NombreProveedor_Tab3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextFieldl_DireccionProveedor_Tab3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextField_TelefonoProveedor_Tab3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextField_CodigoProducto_Tab3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTable_Proveedores.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable_Proveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Documento", "Nombre", "Teléfono", "Dirección", "Cod. Producto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable_Proveedores);
        if (jTable_Proveedores.getColumnModel().getColumnCount() > 0) {
            jTable_Proveedores.getColumnModel().getColumn(0).setPreferredWidth(40);
            jTable_Proveedores.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTable_Proveedores.getColumnModel().getColumn(2).setPreferredWidth(50);
            jTable_Proveedores.getColumnModel().getColumn(3).setPreferredWidth(80);
            jTable_Proveedores.getColumnModel().getColumn(4).setPreferredWidth(50);
        }

        jButton_GuardarProveedor_Tab3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_GuardarProveedor_Tab3.setText("Guardar");

        jButton_NuevoProveedor_Tab3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_NuevoProveedor_Tab3.setText("Nuevo");

        jButton_EliminarProveedor_Tab3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_EliminarProveedor_Tab3.setText("Eliminar");

        jButton_ActualizarProveedor_Tab3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_ActualizarProveedor_Tab3.setText("Actualizar");

        javax.swing.GroupLayout jPanel_ProveedorLayout = new javax.swing.GroupLayout(jPanel_Proveedor);
        jPanel_Proveedor.setLayout(jPanel_ProveedorLayout);
        jPanel_ProveedorLayout.setHorizontalGroup(
            jPanel_ProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ProveedorLayout.createSequentialGroup()
                .addGroup(jPanel_ProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_ProveedorLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel_ProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_EliminarProveedor_Tab3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_GuardarProveedor_Tab3, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel_ProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_NuevoProveedor_Tab3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_ActualizarProveedor_Tab3, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                        .addGap(51, 51, 51))
                    .addGroup(jPanel_ProveedorLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_ProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_CodigoProducto_Tab3)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ProveedorLayout.createSequentialGroup()
                                .addComponent(jTextField_IDProveedor_Tab3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_DocumentoProveedor_Tab3))
                            .addComponent(jLabel_NombreProveedor_Tab3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel_TelefonoProveedor_Tab3)
                                .addComponent(jLabel_DireccionProveedor_Tab3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_ProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_DocumentoProveedor_Tab3)
                            .addComponent(jTextField_CodigoProducto_Tab3)
                            .addComponent(jTextField_NombreProveedor_Tab3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldl_DireccionProveedor_Tab3)
                            .addComponent(jTextField_TelefonoProveedor_Tab3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel_ProveedorLayout.setVerticalGroup(
            jPanel_ProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ProveedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_ProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_ProveedorLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel_ProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_DocumentoProveedor_Tab3)
                            .addComponent(jTextField_DocumentoProveedor_Tab3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_IDProveedor_Tab3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel_ProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_NombreProveedor_Tab3)
                            .addComponent(jTextField_NombreProveedor_Tab3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel_ProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_DireccionProveedor_Tab3)
                            .addComponent(jTextFieldl_DireccionProveedor_Tab3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel_ProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_TelefonoProveedor_Tab3)
                            .addComponent(jTextField_TelefonoProveedor_Tab3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel_ProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_CodigoProducto_Tab3)
                            .addComponent(jTextField_CodigoProducto_Tab3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel_ProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_GuardarProveedor_Tab3)
                            .addComponent(jButton_NuevoProveedor_Tab3))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel_ProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_ActualizarProveedor_Tab3)
                            .addComponent(jButton_EliminarProveedor_Tab3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab3", jPanel_Proveedor);

        jLabel_CodigoProducto_Tab4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_CodigoProducto_Tab4.setText("Código:");

        jLabel_NombreProducto_Tab4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_NombreProducto_Tab4.setText("Nombre:");

        jLabel_CantidadProducto_Tab4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_CantidadProducto_Tab4.setText("Cantidad:");

        jLabel_PrecioVenta_Tab4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_PrecioVenta_Tab4.setText("Precio de Venta:");

        jLabel_PrecioCompra_Tab4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_PrecioCompra_Tab4.setText("Precio de Compra:");

        jTextField_CodigoProducto_Tab4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextField_NombreProducto_Tab4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextField_CantidadProducto_Tab4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextField_PrecioVenta_Tab4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextField_PrecioCompra_Tab4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel_ProveedorProducto_Tab4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_ProveedorProducto_Tab4.setText("Proveedor:");

        jComboBox_ProveedorProducto_Tab4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTable_Productos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable_Productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Cantidad", "Precio de Compra", "Precio de Venta", "Proveedor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable_Productos);
        if (jTable_Productos.getColumnModel().getColumnCount() > 0) {
            jTable_Productos.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTable_Productos.getColumnModel().getColumn(1).setPreferredWidth(80);
            jTable_Productos.getColumnModel().getColumn(2).setPreferredWidth(10);
            jTable_Productos.getColumnModel().getColumn(3).setPreferredWidth(50);
            jTable_Productos.getColumnModel().getColumn(4).setPreferredWidth(50);
            jTable_Productos.getColumnModel().getColumn(5).setPreferredWidth(60);
        }

        jButton_GuardarProducto_Tab4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_GuardarProducto_Tab4.setText("Guardar");

        jButton_ActualizarProducto_Tab4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_ActualizarProducto_Tab4.setText("Actualizar");

        jButton_BorrarProducto_Tab4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_BorrarProducto_Tab4.setText("Borrar");

        jButton_NuevoProducto_Tab4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_NuevoProducto_Tab4.setText("Nuevo");

        jButton_GenerarReporte_Tab4.setBackground(new java.awt.Color(204, 204, 255));
        jButton_GenerarReporte_Tab4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_GenerarReporte_Tab4.setText("Generar Reporte");

        javax.swing.GroupLayout jPanel_ProductosLayout = new javax.swing.GroupLayout(jPanel_Productos);
        jPanel_Productos.setLayout(jPanel_ProductosLayout);
        jPanel_ProductosLayout.setHorizontalGroup(
            jPanel_ProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ProductosLayout.createSequentialGroup()
                .addGroup(jPanel_ProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_ProductosLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel_ProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel_ProductosLayout.createSequentialGroup()
                                .addGroup(jPanel_ProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel_ProveedorProducto_Tab4)
                                    .addComponent(jLabel_PrecioCompra_Tab4)
                                    .addComponent(jLabel_PrecioVenta_Tab4)
                                    .addComponent(jLabel_CantidadProducto_Tab4)
                                    .addComponent(jLabel_NombreProducto_Tab4)
                                    .addGroup(jPanel_ProductosLayout.createSequentialGroup()
                                        .addComponent(jTextField_IDProducto_Tab4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel_CodigoProducto_Tab4)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel_ProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBox_ProveedorProducto_Tab4, 0, 148, Short.MAX_VALUE)
                                    .addComponent(jTextField_PrecioCompra_Tab4)
                                    .addComponent(jTextField_PrecioVenta_Tab4)
                                    .addComponent(jTextField_CantidadProducto_Tab4)
                                    .addComponent(jTextField_NombreProducto_Tab4)
                                    .addComponent(jTextField_CodigoProducto_Tab4)))
                            .addGroup(jPanel_ProductosLayout.createSequentialGroup()
                                .addGroup(jPanel_ProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton_BorrarProducto_Tab4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton_GuardarProducto_Tab4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48)
                                .addGroup(jPanel_ProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton_ActualizarProducto_Tab4, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                    .addComponent(jButton_NuevoProducto_Tab4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel_ProductosLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jButton_GenerarReporte_Tab4)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_ProductosLayout.setVerticalGroup(
            jPanel_ProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel_ProductosLayout.createSequentialGroup()
                .addGroup(jPanel_ProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_ProductosLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel_ProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_CodigoProducto_Tab4)
                            .addComponent(jTextField_CodigoProducto_Tab4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_IDProducto_Tab4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_ProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_NombreProducto_Tab4)
                            .addComponent(jTextField_NombreProducto_Tab4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_ProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_CantidadProducto_Tab4)
                            .addComponent(jTextField_CantidadProducto_Tab4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_ProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_PrecioVenta_Tab4)
                            .addComponent(jTextField_PrecioVenta_Tab4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_ProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_PrecioCompra_Tab4)
                            .addComponent(jTextField_PrecioCompra_Tab4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_ProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_ProveedorProducto_Tab4)
                            .addComponent(jComboBox_ProveedorProducto_Tab4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel_ProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_GuardarProducto_Tab4)
                            .addComponent(jButton_ActualizarProducto_Tab4))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel_ProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_BorrarProducto_Tab4)
                            .addComponent(jButton_NuevoProducto_Tab4))
                        .addGap(18, 18, 18)
                        .addComponent(jButton_GenerarReporte_Tab4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel_ProductosLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab4", jPanel_Productos);

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Cliente", "Vendedor", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(20);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(60);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(60);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(60);
        }

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Exportar PDF");

        javax.swing.GroupLayout jPanel_VentasLayout = new javax.swing.GroupLayout(jPanel_Ventas);
        jPanel_Ventas.setLayout(jPanel_VentasLayout);
        jPanel_VentasLayout.setHorizontalGroup(
            jPanel_VentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_VentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 918, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel_VentasLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addGap(38, 38, 38)
                .addComponent(jTextField_IDVenta_Tab5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_VentasLayout.setVerticalGroup(
            jPanel_VentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_VentasLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel_VentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jTextField_IDVenta_Tab5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab5", jPanel_Ventas);

        jLabel_NIT_Empresa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_NIT_Empresa.setText("NIT:");

        jLabel_Nombre_Empresa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_Nombre_Empresa.setText("Nombre:");

        jLabel_Telefono_Empresa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_Telefono_Empresa.setText("Teléfono:");

        jLabel_Direccion_Empresa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_Direccion_Empresa.setText("Dirección");

        jLabel_DatosEmpresa.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_DatosEmpresa.setText("Datos de la Empresa");

        jTextField_NIT_Empresa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextField_Telefono_Empresa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextField_Direccion_Empresa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jButton_Guardar_DatosEmpresa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_Guardar_DatosEmpresa.setText("Guardar");

        javax.swing.GroupLayout jPanel_InformacionLayout = new javax.swing.GroupLayout(jPanel_Informacion);
        jPanel_Informacion.setLayout(jPanel_InformacionLayout);
        jPanel_InformacionLayout.setHorizontalGroup(
            jPanel_InformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_InformacionLayout.createSequentialGroup()
                .addGroup(jPanel_InformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_InformacionLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(jPanel_InformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_NIT_Empresa)
                            .addComponent(jLabel_Telefono_Empresa)
                            .addComponent(jTextField_NIT_Empresa)
                            .addComponent(jTextField_Telefono_Empresa, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE))
                        .addGap(100, 100, 100)
                        .addGroup(jPanel_InformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_Nombre_Empresa)
                            .addComponent(jLabel_Direccion_Empresa)
                            .addComponent(jTextField2)
                            .addComponent(jTextField_Direccion_Empresa, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)))
                    .addGroup(jPanel_InformacionLayout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(jLabel_DatosEmpresa))
                    .addGroup(jPanel_InformacionLayout.createSequentialGroup()
                        .addGap(324, 324, 324)
                        .addComponent(jButton_Guardar_DatosEmpresa)))
                .addContainerGap(275, Short.MAX_VALUE))
        );
        jPanel_InformacionLayout.setVerticalGroup(
            jPanel_InformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_InformacionLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel_DatosEmpresa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(jPanel_InformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Nombre_Empresa, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_NIT_Empresa, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_InformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_NIT_Empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90)
                .addGroup(jPanel_InformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Direccion_Empresa, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_Telefono_Empresa, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_InformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Telefono_Empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Direccion_Empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(jButton_Guardar_DatosEmpresa)
                .addGap(86, 86, 86))
        );

        jTabbedPane1.addTab("tab6", jPanel_Informacion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_BarraBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_Img_Encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 943, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel_Img_Encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
            .addComponent(jPanel_BarraBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_NombreCliente_Tab1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_NombreCliente_Tab1ActionPerformed

    }//GEN-LAST:event_jTextField_NombreCliente_Tab1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_ActualizarCliente_Tab2;
    private javax.swing.JButton jButton_ActualizarProducto_Tab4;
    private javax.swing.JButton jButton_ActualizarProveedor_Tab3;
    private javax.swing.JButton jButton_BorrarProducto_Tab4;
    private javax.swing.JButton jButton_Clientes;
    private javax.swing.JButton jButton_EliminarCliente_Tab2;
    private javax.swing.JButton jButton_EliminarProveedor_Tab3;
    private javax.swing.JButton jButton_Eliminar_Tab1;
    private javax.swing.JButton jButton_GenerarReporte_Tab4;
    private javax.swing.JButton jButton_GenerarVenta_Tab1;
    private javax.swing.JButton jButton_GuardarCliente_Tab2;
    private javax.swing.JButton jButton_GuardarProducto_Tab4;
    private javax.swing.JButton jButton_GuardarProveedor_Tab3;
    private javax.swing.JButton jButton_Guardar_DatosEmpresa;
    private javax.swing.JButton jButton_Información;
    private javax.swing.JButton jButton_NuevaVenta;
    private javax.swing.JButton jButton_NuevoCliente_Tab2;
    private javax.swing.JButton jButton_NuevoProducto_Tab4;
    private javax.swing.JButton jButton_NuevoProveedor_Tab3;
    private javax.swing.JButton jButton_Productos;
    private javax.swing.JButton jButton_Proveedor;
    private javax.swing.JButton jButton_Ventas;
    private javax.swing.JComboBox<String> jComboBox_ProveedorProducto_Tab4;
    private javax.swing.JLabel jLabel_CantidadCompra_Tab1;
    private javax.swing.JLabel jLabel_CantidadProducto_Tab4;
    private javax.swing.JLabel jLabel_CodigoProducto_Tab1;
    private javax.swing.JLabel jLabel_CodigoProducto_Tab3;
    private javax.swing.JLabel jLabel_CodigoProducto_Tab4;
    private javax.swing.JLabel jLabel_CorreoCliente_Tab2;
    private javax.swing.JLabel jLabel_DatosEmpresa;
    private javax.swing.JLabel jLabel_DireccionCliente_Tab2;
    private javax.swing.JLabel jLabel_DireccionProveedor_Tab3;
    private javax.swing.JLabel jLabel_Direccion_Empresa;
    private javax.swing.JLabel jLabel_DocumentoCliente_Tab1;
    private javax.swing.JLabel jLabel_DocumentoCliente_Tab2;
    private javax.swing.JLabel jLabel_DocumentoProveedor_Tab3;
    private javax.swing.JLabel jLabel_Img_Encabezado;
    private javax.swing.JLabel jLabel_Logo;
    private javax.swing.JLabel jLabel_NIT_Empresa;
    private javax.swing.JLabel jLabel_NombreCliente_Tab1;
    private javax.swing.JLabel jLabel_NombreCliente_Tab2;
    private javax.swing.JLabel jLabel_NombreProducto_Tab1;
    private javax.swing.JLabel jLabel_NombreProducto_Tab4;
    private javax.swing.JLabel jLabel_NombreProveedor_Tab3;
    private javax.swing.JLabel jLabel_Nombre_Empresa;
    private javax.swing.JLabel jLabel_PrecioCompra_Tab1;
    private javax.swing.JLabel jLabel_PrecioCompra_Tab4;
    private javax.swing.JLabel jLabel_PrecioVenta_Tab4;
    private javax.swing.JLabel jLabel_ProveedorProducto_Tab4;
    private javax.swing.JLabel jLabel_Stock_Tab1;
    private javax.swing.JLabel jLabel_TelefonoCliente_Tab2;
    private javax.swing.JLabel jLabel_TelefonoProveedor_Tab3;
    private javax.swing.JLabel jLabel_Telefono_Empresa;
    private javax.swing.JLabel jLabel_TotalPagar_Tab1;
    private javax.swing.JLabel jLabel_ValorPagar_Tab1;
    private javax.swing.JPanel jPanel_BarraBusqueda;
    private javax.swing.JPanel jPanel_Clientes;
    private javax.swing.JPanel jPanel_Informacion;
    private javax.swing.JPanel jPanel_NuevaVenta;
    private javax.swing.JPanel jPanel_Productos;
    private javax.swing.JPanel jPanel_Proveedor;
    private javax.swing.JPanel jPanel_Ventas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable_Clientes;
    private javax.swing.JTable jTable_Productos;
    private javax.swing.JTable jTable_Proveedores;
    private javax.swing.JTable jTable_Venta_Tab1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField_CantidadCompra_Tab1;
    private javax.swing.JTextField jTextField_CantidadProducto_Tab4;
    private javax.swing.JTextField jTextField_CodigoProducto_Tab1;
    private javax.swing.JTextField jTextField_CodigoProducto_Tab3;
    private javax.swing.JTextField jTextField_CodigoProducto_Tab4;
    private javax.swing.JTextField jTextField_CorreoCliente_Tab2;
    private javax.swing.JTextField jTextField_DireccionCliente_Tab1;
    private javax.swing.JTextField jTextField_DireccionCliente_Tab2;
    private javax.swing.JTextField jTextField_Direccion_Empresa;
    private javax.swing.JTextField jTextField_DocumentoCliente_Tab1;
    private javax.swing.JTextField jTextField_DocumentoCliente_Tab2;
    private javax.swing.JTextField jTextField_DocumentoProveedor_Tab3;
    private javax.swing.JTextField jTextField_IDCliente_Tab2;
    private javax.swing.JTextField jTextField_IDProducto_Tab1;
    private javax.swing.JTextField jTextField_IDProducto_Tab4;
    private javax.swing.JTextField jTextField_IDProveedor_Tab3;
    private javax.swing.JTextField jTextField_IDVenta_Tab5;
    private javax.swing.JTextField jTextField_NIT_Empresa;
    private javax.swing.JTextField jTextField_NombreCliente_Tab1;
    private javax.swing.JTextField jTextField_NombreCliente_Tab2;
    private javax.swing.JTextField jTextField_NombreProducto_Tab1;
    private javax.swing.JTextField jTextField_NombreProducto_Tab4;
    private javax.swing.JTextField jTextField_NombreProveedor_Tab3;
    private javax.swing.JTextField jTextField_PrecioCompra_Tab1;
    private javax.swing.JTextField jTextField_PrecioCompra_Tab4;
    private javax.swing.JTextField jTextField_PrecioVenta_Tab4;
    private javax.swing.JTextField jTextField_Stock_Tab1;
    private javax.swing.JTextField jTextField_TelefonoCliente_Tab2;
    private javax.swing.JTextField jTextField_TelefonoProveedor_Tab3;
    private javax.swing.JTextField jTextField_Telefono_Empresa;
    private javax.swing.JTextField jTextFieldl_DireccionProveedor_Tab3;
    // End of variables declaration//GEN-END:variables
}
